### ISSUE TITLE
Remove error_log()

### ISSUE THREAD

**Issue by salcode** [csalzano/wp-api-manipulate-meta#1]
This is a cool plugin. 👍 

Just a heads up, you've got an `error_log()` statement on [line 84](https://github.com/csalzano/wp-api-manipulate-meta/blob/fa4557022f5793e5f1e3f1b7b2307f27f74a1867/wp-api-manipulate-meta.php#L84).

I'm guessing this is leftover from development (I know I've done that many times).

Thanks for building and sharing this.

**Comment by csalzano** [comment]
For sure! Thanks for giving it a once over & finding issues.
