### ISSUE TITLE
Do these REST API endpoints require an authenticated user?

### ISSUE THREAD

**Issue by salcode** [csalzano/wp-api-manipulate-meta#2]
Unless I'm missing something, and I'm not overly familiar with adding WP REST API endpoints so I apologize if I am but it looks like the endpoints created allow anyone to read or write via the WP REST API without authentication.

I know that when I use certain endpoints (e.g. for creating a new user) I must authenticate (usually by including a nonce value), however it looks like this is not necessary for this plugin and anyone could read or write.

**Comment by csalzano** [comment]
Sorry, just saw this now. You're right, I need to specify a `permission_callback` when registering the routes. Thanks!

**Comment by csalzano** [comment]
Fixed, thanks again https://github.com/csalzano/wp-api-manipulate-meta/commit/67c4fc8771fd2110a35c742ef349ff58351f01ca
